# Generated by Django 4.0 on 2022-04-15 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=150)),
                ('p_type', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('p_price', models.IntegerField()),
                ('p_amount', models.IntegerField()),
            ],
            options={
                'ordering': ['p_type'],
            },
        ),
    ]
